/* https://leetcode.com/problems/find-the-difference/description/ 
 * Given two strings s and t which consist of only lowercase letters.

 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        char r = 0;
        int i, j =0;
        for (i = 0; i< s.length(); i++)
            r ^= s.charAt(i);
        for (j = 0; j< t.length(); j++)
            r ^= t.charAt(j);
        return r;
    }
}

class Solution2 {
    public char findTheDifference(String s, String t) {
        int n = t.length();
        char c = t.charAt(n-1);
        for (int i = 0; i<n-1; i++){
            c^=s.charAt(i);
            c^=t.charAt(i);
        }
        return c;
    }
}
